#!/bin/bash
# create express app
npm install express-generator -g

express backend
pushd backend

# start app
npm install
PORT=3001 npm start 
popd
# Now you can use the browser and see the webpage on http://localhost:3000/
